turingschool/portfolios

20150814-fred_block-m4.markdown
new file:   20150814-fred_block-m4.markdown
=> Fred Block

students/michelle_golle/20150814-michelle_golle-m4.markdown
=> Ready to merge: michelle's portfolio

students/kyle_henson/20150807-kyle_henson-m4.markdown
=> Starting my portfolio

students/kristina_brown/20150814-kristina_brown-m4.markdown
kristina's portfolio: forgot the links to my final assessment
=> Kristina's the links to my final assessment

20150914-tracy_caruso-m4.markdown, DJ_SAMPLE.md
=> ready to merge

students/chris_cenatiempo/20150814-chris_cenatiempo-m1.markdown
=> WIP My Portfolio

students/mimi_schatz/20150813-mimi_schatz-m1.md
in progress, awaiting final assessment grades
=> Mimi_Schatz

students/matt_ewell/20150814-matt_ewell-m1.markdown
Ready pending final project scores
=> Matt ewell

students/george_hudson/20150814-george_hudson-m1.markdown
Mostly filled out besides assessment
=> George hudson

students/regis_boudinot/20150814-regis_boudinot-m1.markdown
Added my areas of emphasis. Still going to work on that one.
Added my attendance so far.
Added one example of how I played a part.
=> Done: Added Sales Engine 

students/adamjensen/20150814-adamjensen-m1.markdown
=> starting portfolio

students/sally_macnicholas/20150814-sally_macnicholas-m3.markdown
Ready to merge. Please pass me.
=> portfolio submission

students/drew_conly/20150813-drew_conly-m2.md
All assessments and projects now accounted for.
=> Drew conly

students/rick_bacci/20150814-rick_bacci-m3.markdown
=> start my profile

students/sebastian_abondano/20150814-sebastian_abondano-m2.markdown
Missing final evaluation results and LSoO results.
=> Sebastian Abondano M2

students/20150814-marla_brizel-m2.markdown
M2 portfolio for Marla Brizel
This PR is ready to merge.
=> Marla Brizel - Ready to Merge

students/samson_brock/20150814-samson_brock-m2.markdown
Complete, and ready for merging now.
=> Add Samson Brock's Module 2 Portfolio

students/20150814-max-millington-m2.markdown, template.markdown
=> Max Millington

students/alex_tideman/20150814-alex_tideman-m2.markdown
Initial draft of portfolio - WIP
=> Alex Tideman - WIP

students/lovisa_svallingson/20150814-lovisa_svallingson-m2.md
=> [WIP] Lovisa Svallingson Portfolio

students/jason_wright/20150814-jason_wright-m2.markdown
=> jasonwright

students/1508/jason-pilz/20151002-jason-pilz-m1.markdown.md
=> Jason pilz

students/1503/sally-macnicholas/20151001-sallymacnicholas-m4.markdown
=> sally macnicholas portfolio submission

students/max_tedford/20151002-max_tedford-m4.markdown
=> Maxtedford

students/1508/john-slota/20151001-john-slota-m1.markdown
=> portfolio done

portfolio.md
=> portfolio.md

students/1505/marla-brizel/20151002-marla-brizel-m3.markdown
=> add marla brizel m3 portfolio

students/marybeth_burch/20151002-marybeth-burch-m2.markdown
MB Burch complete Mod 2 Portfolio
=> MB Burch Mod 2 Portfolio

students/20151002-max-millington-m3.markdown
=> updated module 3 portfolio 

students/lovisa_svallingson/20151002-lovisa_svallingson-m3.md
* add personal project details
* add feedback from peers
=> Add Lovisa's portfolio

students/1507/matt-hecker/20150824-matt-hecker-m2.md
=> Add Matthew Hecker's M2 Portfolio

students/1505/dave-maurer/20151002-dave-maurer-m3.markdown
I already had a folder in here, but this one follows the new directory tree format adding my cohort, so I created the request for master.
=> newer better mod3 portfolio

students/1505/dmitry-vizersky/20151002-dmitry-vizersky-m3.html, students/1505/dmitry-vizersky/20151002-dmitry-vizersky-m3.markdown
I have a build system that spits out a ".html" page for my markdown document so as to view in the browser.
=> Module-3 Portfolio

students/1507/alon-waisman/20151120-alon-waisman-m3.markdown
=> Alon Waisman M3 portfolio

students/1505/max-millington/20151119-max-millington-m4.markdown
=> portfolio review

students/lovisa_svallingson/20151120-lovisa_svallingson-m4.md
Add Lovisa's portfolio for m4.
=> Add Lovisa's portfolio m4

students/1510/alexis-navarrete/20151120-alexis-navarrete-m1.markdown
=> Alexis Navarrete's M1 Portfolio 

students/1510/20151120-brant-wellman-m1.markdown
=> Brant Wellman portfolio - WIP

students/1510/20151120-joe-perry-m1.markdown
=> Joe Perry M1 Portfolio

students/1508/emily-dowdle/20151002-emily_dowdle-m2.markdown
=> Module 2 Portfolio

students/1511/adam_hundley/20160120_adam_hundley_m1.md
=> adam hundley portfolio

students/1505/alex-tideman/20151002-alex-tideman-m3.markdown, students/1505/alex-tideman/20151120-alex-tideman-m4.markdown, students/alex_tideman/20151119-alex_tideman-m4.markdown
Fix merge conflict for Mod3 feedback.
=> Alex tideman

students/1511/brennan-holtzclaw/brennan-holtzclaw-m1.md
Just waiting on Final project assessment scores...
=> [WIP] Brennan-Holtzclaw M-1 portfolio

students/1511/brian-rippeto/20160120-brian-rippeto-m1.md
=> Brian Portfolio

students/1511/chelsea-johnson/chelsea-johnson-m1.markdown
Here is my portfolio! Added it to 1511 directory.
=> Chelsea Johnson portfolio

students/1511/julian-feliciano.md
Only missing Headcount which is due on Thursday
=> Add Julian Feliciano 1511 portfolio

students/1511/matt_pindell.md
added matt_pindell.md to 1511 folder
=> added matt_pindell.md to 1511 folder

students/1507/matt-hecker/20160121-matt-hecker-m4.md
=> Matthew Heckers m4 portfolio

students/1507/travis-haby/20150121-travis-haby-m4
=> Travis Haby Module 4 Portfolio

students/1505/erik-butcher/20160121-erik-butcher-m4.md
Future given feedback may be coming!
=> Create 1512 timeblock porftolio

students/1507/rick-bacci/20150814-rick-bacci-m3.markdown, students/1507/rick-bacci/20151002-rick_bacci-m3.markdown, students/1507/rick-bacci/20151120-rick-bacci-m4.markdown, students/1507/rick-bacci/20160122-rick-bacci-m4.markdown
add all portfolios for Rick Bacci
=> add previous portfolios

students/1511/admir-draganovic/20160121-admir-draganovic-m1.markdown
=> Admir Portfilio

students/1508/sekhar-paladugu/20151120-sekhar-paladugu-m3.markdown
There are small typos here I will fix later
=> module 3 portfolio done

students/1508/emily-dowdle/20160121-emily_dowdle_m3.md
=> Mod 3 portfolio

students/1511/20150122-marina-corona-m1.markdown
=> Add Marinas portfolio

students/1511/brian-rippeto/20160120-brian-rippeto-m1.md
I went over my Enigma File.io refactor with Lovisa. Let me know if you guys need anything more to address that concern.
=> Final project added - enigma refactor completed

students/1508/jhun-de-andres/20160121-jhun-de-andres-m3.markdown
=> posting up my m3 portfolio

students/1510/dan-winter/20151221-dan-winter-m2.markdown, students/1510/dan-winter/20160121-dan-winter-m2.markdown
=> Dan Winter M2 Portfolio

students/1507/jeff-ruane/20160122-jeff_ruane-m4.markdown
Updated with feedback to and from peers.
=> Jeff Ruane Module 4 Portfolio - Updated

students/1510/james-crockett/2_module_portfolio.markdown
=> Add portfolio 2

students/1511/brennan-holtzclaw/brennan-holtzclaw-m1.md
Maybe this will bump that 'group work and projects' up to a 4?
=> adding scores for final project. 

students/1511/chelsea-johnson/chelsea-johnson-m1.markdown
=> Chelsea Johnson M1 Portfolio

students/1507/matt-hecker/20160121-matt-hecker-m4.md
This adds feed back to my module 4 port
=> added feedback to module 4 portfolio

students/1508/emily-dowdle/20160310-emily_dowdle-m4.md
=> Mod 4 portfolio for Emily Dowdle

students/1602/ashwin-rao/ashwin_rao.markdown, students/1602/ashwin-rao/jungle_beats_assessment.markdown, students/1602/ashwin-rao/night_writer_assessment.markdown
This is the final version of my portfolio. It includes as projects, assessments, and other requirements.
=> m1 portfolio for Ashwin Rao

students/1602/claudia-kiesenhofer/ClaudiaKiesenhofer.markdown, students/1602/claudia-kiesenhofer/SAMPLE.markdown
All required parts of the portfolio have been added
- including both assessments
- 2 individual projects
- 2 partner projects
- feedback
- DTR
- blog post
- pull requests
- Readme file
=> Claudia portfolio

students/1602/patrick-hardy/portfolio.markdown
This portfolio includes all requested information
=> Patrick Hardy Portfolio

students/1510/joe-perry/20160120-joe-perry-m2.markdown
Conflict resolved, adding JP mod 2 portfolio.
=> JP mod 2 is added

students/1510/beth-sebian/20160311-beth-sebian-m3.markdown
=> Add module 3 portfolio content

students/1602/thom-pickett/thomp.md
* fixed markdown spacing issues 
* fixed typos
* updated community section
=> thom pickett portfolio update

students/1510/joe-perry/20160310-joe-perry-m3.markdown
=> JP mod3 portfolio is added

students/1511/adrienne-domingus/20160311-adrienne-domingus-m2.md
=> Add Adrienne mod2 portfolio

students/1511/brian-rippeto/20160120-brian-rippeto-m1.md, students/1511/brian-rippeto/20160201-brian-rippeto-m2.md
=> Brian Rippeto's mod 2 portfolio

students/1510/penney-garrett/2016-penney-garrett-m4.md
=> Penney Garrett M4 portfolio

students/1510/joe-perry/20160427-joe-perry-m4.markdown
=> JP m4 portfolio

students/1602/20160428-alireza-andersen-m1.markdown
Alireza Andersen Mod 2 Portfolio.
=> Alireza Andersen Mod 2 Portfolio

students/1602/andrew-thompson/20160311-andrew-thompson-m1.md, students/1602/andrew-thompson/20160429-andrew-thompson-m2.md
Added Module 2 portfolio
Change Mod 1 file name
=> Drew Thompson Mod 2 Portfolio

students/1602/ashwin-rao/20160429-ashwin-rao-m2.markdown, students/1602/ashwin-rao/2module/ashwin_rao_module_2.markdown
This is the final version of my portfolio for my mod 2 assessment.
=> Portfolio for Ashwin Rao ready for Apr 28, 2016 assessment

students/1602/christopher-soden/20160429-christopher-soden-m2.markdown, students/1602/christopher-soden/M2_Mid_Mod_Assessment.txt
Add M2 portfolio. Add Little Shop scores.
=> Christopher Soden M2 Portfolio

students/1603/robert-jaeger/20160429-robert-jaeger-m1.markdown
End-of-module portfolio review
=> Robert jaeger

students/1511/brian-rippeto/20160201-brian-rippeto-m2.md, students/1511/brian-rippeto/20160321-brian-rippeto-m3.md
=> Mod 3 portfolio complete

students/1602/mark-miranda/20150311-mark-miranda.m1.markdown
=> Add Mark Miranda Portfolio for Mod 2

students/1602/hedy-w/hedy-wutang.md
=> Wonderwoo's

students/1602/sal-espinosa/20160429-sal-espinosa-m2.md
Mod 2 Portfolio for Sal ready for review.
=> Sal Mod 2 Portfolio

students/1602/thom-pickett/thomp-mod2.md
Added my portfolio for module two to my directory in students
=> Add thoms mod2 portfolio

students/1511/adam-hundley/20160617-adam-hundley-m4.md
=> module 4 portfolio

students/1511/erinna-chen/20160617-erinna-chen-m4.markdown
=> Module 4 Portfolio- Erinna Chen

students/1511/nicholas-dorans/20160616-nicholas_droans_m4.md, students/Archive/1510/aaron-greenspan/20150429-aaron-greenspan-m4.md
Sorry bout that lol, I was using his portfolio as a template and forgot to copy it over to my file. @rrgayhart
=> Mod 4 Portfolio

students/1511/brian-rippeto/20160321-brian-rippeto-m3.md, students/1511/brian-rippeto/20160616-brian-rippeto-m4.md
=> Brian mod 4 portfolio complete

students/1511/julian-feliciano/20160615-julian-feliciano-m4.md
Forgot to add my scores. Woops!
=> Add scores

students/1603/lucy-fox/20160617-lucy-fox-m2.markdown
Submission for Lucy Fox M2 portfolio.
=> Mod 2 Portfolio

students/1603/anna-weisbrodt/20160617-anna-weisbrodt-m2.markdown
=> anna weisbrodt mod2 portfolio

students/1602/andrew-thompson/20160617-andrew-thompson-m3.md
Mod 3 Portfolio for (An)Drew Thompson
=> Module 3 Portfolio

students/1605/matthew-campbell/20160617-matthew-campbell-m1.markdown, students/1605/matthew-campbell/template.markdown
=> Matt Campbell's Portfolio

students/1602/jonathan-liss/20160617-jonathan-liss-m3.md
=> jon liss mod3 portfolio

students/1603/jennifer-soden/20160616-jenny-soden-m2.md
Portfolio submission for module 2
=> 20160429 jennifer soden

students/1603/karina-gonzalez/20160615-karina-gonzalez-m2.markdown
Pull request for mod 2 portfolio... but I already uploaded the file into the repository so I'm just doing this to be safe...
=> karina- added mod 2 portfolio

students/1603/erin-greenhalgh/20160617-erin-greenhalgh-m2
Erin Greenhalgh's Mod 2 Portfolio
=> 20160617-erin-greenhalgh-m2.markdown

students/1602/kris-foss/20160616-Kris-Foss-m3.md
Adds my mod3.md for my portfolio review tomorrow.  Thank you!
=> adds mod3 portfolio

students/1602/matt-pindell/2016-matt-pindell-m2.markdown, students/1602/matt-pindell/2016-matt-pindell-m3.markdown
=> Add mod 3 portfolio

students/1602/ling-tran/201606-ling-tran-m3.md, students/1602/ling-tran/20160616-ling-tran-m3-portfolio.md, students/1602/ling-tran/review_16APR29.md
Complete creation of module 3 portfolio with required content
=> Ling Tran - module 3 portfolio complete

students/1606-front/casey-cross/template.md
Please add us, we do exist. :)
=> Add 1606 front end folder and folder for myself

students/1606-front/maryjane-valade/template.md
Is this the proper way to make my folder?
=> new folder and template

students/1602/alex-navarrete/20160804-alex-navarrete-m4.md
=> portfolio!

students/1602/mark-miranda/20160805-mark-miranda.m4.markdown
=> add mod 4 portfolio for mark miranda

students/1602/sal-espinosa/20160804-sal-espinosa-m4.md
Adds final portfolio submission for Sal.
=> Add mod 4 portfolio submission for Sal

students/1602/jared-roth/20160805-jared-roth-m4.markdown
You see, the portfolio is like a tire, the more it spins, the dizzier it gets.
=> Add Jared Roth's M4 portfolio

students/1602/claudia-kiesenhofer/ClaudiaKiesenhofer_module4_portfolio.md
My last Turing School portfooollliiiiooooo
=> 1602 Claudia module 4 portfolio

students/1602/ling-tran/20160804-ling-tran-m4-portfolio.md, template.markdown
Complete for requirements with self-solicited feedback
=> complete lingtran-m4-portfolio

students/1602/marina-corona/marinacorona08032016Mo4.md
=> Complete personal feedback

students/1602/kami-boers/20160804-kami-boers-m4.md
=> kami boers mod 4 portfolio

students/1602/gurusundesh-khalsa/20160804-gurusundesh-khalsa-m4.md
=> Update gurusundesh khalsa m4 portfolio

students/1606-back/bryan-goss/template.md
=> Final submission

students/1605/tommasina-miller/08052016-tommasina-miller-m2.md
This is my module 2 portfolio.
=> Created mod2 portfolio

students/1606-back/jasmin-hudacsek/20160805-jasmin-hudacsek-m1.markdown, students/1606-back/jasmin-hudacsek/jasmin-hudacsek-m1.md
Portfolio is ready pending Black Thursday eval and scores.
=> Add Jasmin Hudacsek M1 Portfolio

students/1606-front/madison-kerndt/20160804-madison-kerndt-m1.markdown
Thank you for all of your extraordinary instruction. I could not have imagined I would have been at this point 6 weeks ago.
=> madison-eval-mod-1

students/1606-front/ben-godfrey/20160805-ben-godfrey-m1.md
=> Mod 1 Markdown for Ben Godfrey.

students/1603/anna-weisbrodt/20160805-anna-weisbrodt-m3.markdown
--add anna weisbrodt mod3 portfolio
=> anna weisbrodt mod3 portfolio

students/1606-back/nate-anderson/201608-nate-anderson-m1.md
adding 201608-nate-anderson-m1.md
=> adding 201608-nate-anderson-m1.md

students/1603/nick-pisciotta/20160804-nick-pisciotta-m3.markdown
=> Mod3 portfolio

students/1605/patrick-wentz/module_2_portfolio.markdown
=> Pat Wentz module 2 portfolio

students/1603/parker-phillips/20160429-parker-phillips-m1.markdown, students/1603/parker-phillips/20160804-parker-phillips-m3.markdown
=> Finished mod 3 portfolio - Parker Phillips

students/1603/jennifer-soden/20160804-jenny-soden-m3.md
Add portfolio for Jenny Soden m3
=> portfolio for m3

students/1605/ryan-flach/20160805-ryan-flach-m2.markdown
Add individual projects
Add group projects and feedback
Add community content information
=> Complete M2 Portfolio

students/1603/kerry-sheldon/20160804-kerry-sheldon-m3.markdown
Never sure if I am doing this right.  Hope so...
=> Kerry Sheldon's mod 3 portfolio

students/1603/robert-jaeger/20160805-robert-jaeger-m3.markdown
Add module 3 portfolio for Robbie Jaeger
=> Add m3 portfolio

students/1603/anna-weisbrodt/20160923-anna-weisbrodt-m4.markdown
--add anna weisbrodt m4 portfolio
=> anna weisbrodt m4 portfolio

students/1606-back/raphael-barbo/20160922-raphael-barbo-m2.markdown
Adding Raphael Barbo - Module 2 Portfolio.
=> 20160922-raphael-barbo-m2.markdown

students/1603/brian-sayler/2016-09-22-brian-sayler-m4.markdown
Adding my module 4 portfolio. Thanks!
=> add Brian's mod4 portfolio

students/1603/nick-pisciotta/20160922-nick-pisciotta-m4.markdown
Final portfolio submission form.
=> Nick M4 portfolio

students/1603/ilana-corson/20160923-ilana-corson-m4.markdown
=> Ilana module 4

students/1603/robert-jaeger/20160923-robert-jaeger-m4.markdown
Added completed portfolio for module 4
=> Robert Jaeger - Add m4 portfolio

students/1603/marcella-wigg/20160922-marcella-wigg-m4.md
=> Marcella Wigg M4 portfolio

students/1603/parker-phillips/20160922-parker-phillips-m4.md, students/1603/parker-phillips/template.markdown
Adding the final portfolio for Parker's time at Turing
=> Parker Phillips' Mod 4 Portfolio

students/1602/kris-foss/20160922-Kris-Foss-m5.md
This might be too much, adds the whole 1602 class back in, but I'm not going to poke it.  I don't need another portfolio mess.
=> adds kris foss mod 5

students/1606-front/dkerr_mod2.markdown
=> added portfolio markup for mod 2

students/1606-front/ben-godfrey/201609022-ben-godfrey-m2.md
=> Ben Godfrey's Completed Mod 2 Portfolio

students/1606-front/casey-metz/20160922-casey-metz-m2.markdown
=> Casey metz

students/1606-front/brett-hevia/20160922-brett_hevia-m2.md
=> Brett Hevia FE Mod 2 Portfolio

students/1606-front/adam-bernard/20160922-adam-bernard-m2.markdown
=> adam bernard mod 2 portfolio

students/1606-front/kirsten-swanson/20160922-kirsten-swanson-mod2.md
module 2 portfolio complete and ready for review
=> Kirsten Swanson-complete mod 2 portfolio

students/1608-back/jason-conrad/template.markdown
Please find attached my filled out Portfolio
=> Jason Conrad Portfolio

students/1608-front/maia-stone/20160923-maia-stone-m1.md
=> Maia Stone Mod 1

students/1608-front/christine-gamble/20160923-christine-gamble-m1.markdown
=> Christine Gamble- 1608FE

students/1608-front/mike-ziccardi/mike-ziccardi.markdown
Mike Ziccardi Portfolio Defense
=> mikeziccardi portfolio defense

students/1605/ryan-flach/20160922-ryan-flach-m3.markdown
- Add area of emphasis and feedback given to Pivot team members
- Add evaluation scores from Pivot project
- Add feedback received from partners in the Pivot project
- Add project description, scores, and feedback given to Pat for Rails Engine
- Add feedback received for Rails Engine
- Add posse and Gear Up reflections
- Add scores from final assessment, template for personal project
=> Complete M3 Portfolio

students/1608-front/kinan-whyte/template.markdown
=> 20160923-Kinan-Whyte-M1.md

students/1608-back/alisher-sadikov/20161110-alisher-sadikov-m2.markdown
created m2 portfolio for alisher sadikov
=> added alisher sadikov m2 portfolio

students/1608-front/mike-ziccardi/modtwo.md
=> mod two portfolio

students/1608-front/maia-stone/20161111-maia-stone-m2.md
✨  ✨  ✨ Maia Stone - Mod 2!! ✨  ✨  ✨ 👏
=> Maia Stone Mod 2 PR

students/1605/christopher-concannon/20161110-chris-concannon-m4.markdown
Completed M4 Portfolio according to rubric
=> Chris Concannon M4

students/1608-front/nick-chambers/nick-chambers-portfolio.md
=> Nick Chambers Portfolio

students/1608-front/gabrielle-procell/20161110-gabi-procell-m2.md
=> Gabi Procell M2 Portfolio submission

students/1603/kerry-sheldon/20161110-kerry-sheldon-m4.markdown
Adds my M4 portfolio
Oh, and I was still in 1603 folder, so I left myself there?!
=> kerry m4 portfolio

students/1605/ryan-flach/20161110-ryan-flach-m4.markdown
- Add initial template and feedback for PD imposter's syndrome workshop
- Add feedback and scores from Idea Box 2.0
- Add reflection to week 1 Gear Up session
- Add reflection from PD negotiation session
- Add Areas of Emphasis, feedback and scores from Jeepney Jump
- Add reflection from week 3 Gear Up session
- Add refecltion from week 4 Protocol session
- Add reflection from week 5 Gear Up session
- Add Scale Up feedback and 3 top job search priorities
- Add feedback from final asssessment and final rubric scores
=> Complete M4 Portfolio

students/1608-front/andrew-crist/20161111-andrew-crist-m2.markdown
=> Andrew Crist - mod2 portfolio submission

students/1605/ryan-flach/20161110-ryan-flach-m4.markdown
- Add required feedback to the Feedback & Community Participation section
- In defense of a 4 for Professional Skills:
- The rubric states:
```
4: Student demonstrates dedication to their professional growth by not only completing the expected deliverable(s) but also pursuing additional opportunities for professional development beyond what is presented in sessions.
```
- In addition to completing expected deliverables, I shadowed at a company for a full-day by taking the initiative to reach out. I also had coffees with two alums, one potential employer, and regularly attend meetups.
- In defense of a 4 for for Group Work & Projects:
- The rubric states:
```
4: Student consistently helps their teammates be their best selves, learn at an accelerated pace, and achieve great results.
```
- …
=> M4 Portfolio Update - Feedback & Community Participation

students/1610-back/drew-palazzari/drew_portfolio
Still need to update with final assessment and final blackthursday score.
=> drew_palazzari_portfolio

students/1606-back/susi-irwin/20161110-susi-irwin-m3.markdown
Here is my Portfolio for Module 3.
=> Susi Irwin - Module 3 Portfolio Submission

students/1610-back/lucy-conklin/template.markdown
=> Lucy conklin

students/1610-back/edilene-cruz/mod_1_portfolio.md
=> edilenes_mod_1_portfolio.md

students/1610-back/molly-brown/20161110-molly-brown-m1.markdown, students/1610-back/molly-brown/template.markdown, template.markdown
=> Molly Brown mod1 portfolio

students/1610-front/kenia-farias/template.markdown
=> Kenia_Farias

students/1606-front/mike-sausa/mike-sausa-mod3.markdown
=> Please pass me, I've got a hungry mouth to feed! (my own)

students/1606-front/kirsten-swanson/20160922-kirsten-swanson-mod2.md, students/1606-front/kirsten-swanson/20161110-kirsten-swanson-mod3.md
=> kirsten swanson - complete module 3

students/1606-back/raphael-barbo/20161110-raphael-barbo-md3.markdown
I have updated the Professional Skills portion of the portfolio as requested. Please let me know if you need anything else.
Best - Rapha Barbo
=> Updated 20161110-raphael-barbo-md3.markdown

M2_template.markdown
@case-eee See my small edits. Created a M2 template. If we decide this looks good, can pre-populate folders with this file.
=> Create M2 markdown with Rubric

students/1608-front/chelsea-skovgaard/mod3portfolio.markdown
Adds Chelsea Skovgaard's Module 3 Portfolio
=> Chelsea Skovgaard Module 3 Portfolio

students/1608-front/gabrielle-procell/20170111-gabi-procell-m3.md
Pending:
* Feedback to me
* Flower exercise
=> Gabi Procell - Adds mod 3 portfolio

students/1610-back/lucy-conklin/lucy_mod_two_portfolio.markdown
Lucy Conklin's Module 2 portfolio.
Evaluation: 1/12/17 8:00am
=> lucy module 2 portfolio

students/1610-back/eric-wahlgren/eric_mod_two_portfolio.markdown
Thanks for reviewing this @case-eee and @s-espinosa
=> Portfolio for module two complete 

students/1606-front/adam-bernard/20160922-adam-bernard-m2.markdown, students/1606-front/adam-bernard/20161110-adam-bernard-m3.markdown
=> Adam Beranrd Mod 3 Front End

students/1606-back/ryan-workman/20170112-ryan-workman-m4.md
=> Workman Mod 4 Portfolio Ready for Evaluation

students/1606-back/jesse-spevack/20170111-jesse-spevack-m4.md
=> Add Jesse Spevack Portfolio Mod 4

students/1606-back/nate-anderson/201701-nate-anderson-m4.md
=> Nate anderson mod4 portfolio

students/1606-back/jasmin-hudacsek/20160113-jasmin-hudacsek-m4.markdown
=> Add Jasmin Hudacsek's M4 Portfolio

students/1610-front/adam-rice/adamrice-1610-m2.markdown
=> Adam Rice Mod 2 FE

students/1606-front/casey-cross/20161111-casey-cross-m3.md, students/1606-front/casey-cross/20170113-casey-cross-m4.md
=> Casey Cross mod4 portfolio

20170113-krystin-villeneuve-m1.markdown, students/1611-front/krystin-villeneuve/20170113-krystin-villeneuve-m1.markdown, template.markdown
This is the markdown for my portfolio. I had to add my own folder.
=> 20170113 krystin villeneuve m1

students/1610-front/dylan-avery/20160112-dylan-avery-m2.markdown, students/1610-front/dylan-avery/dylan_avery.markdown
Hello @joshuajhun @rrgayhart ,
Here is my new Portfolio for Mod2. 
Thanks!
Dylan
🙀 💻
=> new portfolio for mod2

students/1608-back/alisher-sadikov/20170112-alisher-sadikov-m3.markdown
=> add alisher sadikov m3 portfolio

students/1608-back/matt-demarteau/20160310-matt-demarteau.M1.md, students/1608-back/matt-demarteau/20160920-matt-demarteau-M2.md, students/1608-back/matt-demarteau/20170111-matt-demarteau-M3.md, students/1608-back/matt-demarteau/template.md
=> Add Portfolio forlder 1608-back for Matt DeMarteau

students/1610-front/elijah-williams/2017-01-12-Elijah-Williams-Mod2F
This is Elijah Williams' (1610E) portfolio submission for Mod2.
=> Create 2017-01-12-Elijah-Williams-Mod2F file

students/1610-front/eric-sayler/eric_sayler_M2.md
add first draft of mod2 portfolio, still need to include some feedback and professional development deliverables.
=> add mod2 portfolio

students/1606-back/ben-pepper/M3_portfolio.md
Add Scores and start of feedback.
=> add final scores and some feedback.

students/1608-back/megan-talbot/m3portfolio.md
Updated with self directed scores!
=> Megan Update m3portfolio.md

students/1611-back/maria-stenquist/20170112-maria-stenquist-m1.md
-added some scores, fixed minor things
=> updated portfolio

students/1610-front/joshua-small/Joshua-Small-M2-1610-Portfolio
=> Joshua-Small-M2-1610-Portfolio

students/1610-front/noah-peden/Mod 2 Noah Peden Portfolio.md
Here is my portfolio for mod 2! @joshuajhun @rrgayhart
=> mod2 portfolio for noah peden

students/1608-front/mike-ziccardi/mod-2-redo.md
MIKE ZICCARDI PORTFOLIO REVIEW
=> MikeZiccardi 1610 FE

students/1611-back/edilene-cruz/mod_1_1611.md
=> update Edilene's portfolio

students/1608-front/nick-chambers/Nick-Chambers-mod4-portfolio.md
=> nick chambers mod 4 portfolio

students/1608-back/alisher-sadikov/20170302-alisher-sadikov-m4.markdown
add alisher m4 portfolio for some feedback before actual review
=> update alisher sadikov m4 portfolio (ready for final review)

students/1608-back/matt-demarteau/20160201-matt-demarteau-M4.md
=> Final Portfolio for Module 4

students/1608-back/daniel-shin/mod_3_portfolio.markdown
@jcasimir @neight-allen Here is my portfolio for review
=> Create mod 4 portfolio

students/1608-back/nicholas-martinez/NM_Mod4_Portfolio
=> Nick Martinez

students/1608-back/lee-saville/20170301-lee-saville-m4.md
=> Create mod4 portfolio

students/1608-back/daniel-shin/mod_4_portfolio.markdown
=> Daniel Shin mod_4_portfolio.markdown

students/1701-front/dave_hubertus/template.markdown
=> Dave Hubertus Portfolio

students/1701-front/karen_kepner/template.markdown
=> Karen Kepner's Start Portfolio

students/1611-back/cody-borders/20170228-cody-borders-m2.markdown
Needs Little Shop and assessment scores/notes. Flower Exercise is missing, I have it stored somewhere and will update once I find it.
=> Adds Mod 2 Portfolio

students/1611-back/edilene-cruz/mod_2.md
=> adds Edilene's mod 2 portfolio

students/1611-back/james-anderson/20170303_james_anderson_m2.markdown
=> 20170303_james_anderson_m2.markdown

students/1610-back/lucy-conklin/lucy_mod_three_portfolio.markdown
* needs individual project scores
=> Lucy Conklin M3 Portfolio

students/1611-front/tim-brandle/tim-brandle-mod2.markdown
=> Tim Brandle

students/1610-front/elijah-williams/elijah-williams-mod3
I'll update tomorrow after my project eval.
=> Create elijah-williams-mod3 portfolio

students/1608-front/mike-ziccardi/modthree.md
=> mike ziccard mod 3 portfolio

students/1610-front/eric-sayler/eric_sayler_M3.md
=> add mod3 portfolio

students/1610-front/mike-limberg/20170302-Mike-Limberg-M3.md
Still awaiting partner feedback and final project scores. Will update once I receive.
=> Mike Limberg-M3.md

students/1608-back/ben-pepper/M4_portfolio.md
Adds final assessment to portfolio.
@neight-allen
=> Add M4 portfolio.

students/1703-front/lindsay_parker/20170421-lindsay-parker-m1.markdown
=> M1 - 1703 FE - Lindsay Parker

students/1701-back/craig_ness/20170421-craig-ness-m2.markdown
Updating my portfolio for module 2.
=> Craig Ness Update Mod2 Portfolio

students/1701-back/joseph_glass/20170421-joseph-glass-m2.markdown
Mod2 portfolio, waiting on LittleShop evaluation.
=> add mod2 portfolio for joseph_glass

students/1611-back/andrew-wooten/20170421-andrew-wooten-m3.markdown
=> Add M3 Portfolio for Andrew Wooten

students/1610-back/lucy-conklin/lucy_mod_four_portfolio.markdown
Template: Mod4 success document.
=> Adds Lucy's M4 Portfolio

students/1610-front/template/template.markdown
Final assessment scores pending.  I did not see a folder with my name on it in 1610 FE. If this needs to go elsewhere, please let me know.
=> Gabi Procell Mod 4 Promotion Portfolio

students/1701-back/jonathan_kidd/20170420-jonathan-kidd-m2.markdown
Add Jonathan Kidd Module 2 portfolio
=> add 20170420-jonathan-kidd-m2.markdown

students/1610-front/20170421-gabi-procell-m4.md
I have another PR for the template, I wasn't sure where this was supposed to go because I don't have a folder made for me in this repo.
=> Promotion portfolio for Gabi Procell

students/1703-front/evan-miller/20170421-Evan-Miller-m1.markdown
=> evan 1703 frontend mod1

students/1610-front/noah-peden/Mod4 Noah Peden.md
@Alex-Tideman here's my portfolio!
=> mod4 portfolio

students/1611-front/tim-brandle/tim-brandle-mod2.markdown, students/1611-front/tim-brandle/tim-brandle-mod3.markdown
@Tman22 @martensonbj 
Still missing the score from the eval and the personal project.
=> WIP - Mod3 Portfolio

students/1701-back/lauren_oliveri/20170421-lauren-oliveri-m2.markdown
Soooo sorry for delay, please forgive and love me anyway. ❤️
=> Lauren Oliveri Module 2 Portfolio

students/1701-back/maria-stenquist/20170421-maria-stenquist-m2.md
=> add module two portfolio

students/1701-back/natalie_barron/20170420-natalie-barron-m2.markdown
Only thing missing is our Little Shop assessment scores.
=> Mod 2 portfolio update

students/1703-back/20170421-first-last-m1.markdown, students/1703-back/larisa-anderson/20170421-larisa-anderson-m1.markdown
=> Larisa Anderson 1703- BE

students/1703-back/20170421-first-last-m1.markdown, students/1703-back/aaron_olsen/20170421-aaron-olsen-m1.md
First iteration pull on mod 1 portfolio, Aaron Olsen
=> Aaron Olsen Portfolio

students/1701-back/sergey_lukyanenko/20170420-sergey-lukyanenko-m1.markdown
=> Sergey Lukyanenko mod2 portfolio

students/1703-back/tom-soucie/20170421-tom-soucie-m1.markdown
Only 1 file changed - Final Mod1 Portfolio
=> TOM SOUCIE M1-Portfolio

students/1701-back/david_thompson/20170419-riley-thompson-m2.markdown
*does not have MVA feedback or littleshop scores/comments
=> add mod 2 init portfolio Riley T

students/1610-back/michael-schutte/4module_portfoltio_schutte.md
Added updates for open source requirements
=> 1610BE Portfolio (Schutte)

students/1703-back/tom-soucie/20170421-tom-soucie-m1.markdown
TOM SOUCIE - M1 Portfolio with Headcount scores
=> TOM SOUCIE - M1 Portfolio with Headcount scores

students/1703-back/sarah_kirk/20170421-sarah-kirk-m1.markdown
=> Sarah Kirk 1703 Back End

students/1703-back/samuel-lim/20170421-samuel-lim.markdown
Need to add headcount feedback and scores
=> Initial commit of portfolio

students/1703-back/natalia-colome/20170421-natalia-colome-m1.markdown
Complete grades including sanitation, only my feedback from Charlie from headcount is missing
=> Natalia_Colomé_mod1

students/1703-back/joel-lindow/20170421-Joel-Lindow.md
Fixed conflict. Pushing portfolio update
=> push fresh portfolio

students/1703-back/marc-fidelman/20170421-marc-fidelman-m1.md
=> seriously fixed

students/1611-front/kyle-zucker/20170420-kyle-zucker-m3.markdown
=> KZ add feedbacks

students/1611-front/staci-mcwilliams/20170609-staci-mcwilliams-m4.md
@robbiejaeger  @brittanystoroz 
Completed mod four portfolio minus the grades for capstone project.
=> Add mod 4 portfolio for Staci McWilliams

students/1611-front/marissa-reinke/20170607-marissa-reinke-m1.markdown
Create 20170607-marissa-reinke-m1.markdown
=> marissa-reinke-final-portfolio

students/1611-front/rebecca-holt/20170609-rebecca-holt-m4.markdown
=> 20170609-rebecca-holt-m4.mardown

students/1611-front/tim-brandle/npm-debug.log, students/1611-front/tim-brandle/tim-brandle-mod4.markdown
=> Mod-4 portfolio

students/1611-back/courtney-meyerhofer/courtney_meyerhofer_m4.md
=> meyerhofer mod 4 be portfolio update

students/1611-back/james-anderson/20170607_james_anderson_m4.md
@neight-allen @BobGu @case-eee 
This adds a link to the blog post about adding to open source
=> Completes blog post addition to open source

students/1611-back/jonathan-serrano/Jonathan_Serrano_mod_four_portfolio.markdown
Adds Jonathan Serrano's Mod4 Portfolio.md
=> Jonathan Serrano Mod4 Portfolio

students/1705-back/desislava-todorova/20170608-Des-Todorova-m1.md
I wrote a lot more, but I didn't want to disregard the required format for the Portfolio. Would it be okay to make some of the paragraphs  significantly longer? I will add this along with Black Thursday info if it doesn't compromise my Portfolio as a whole. Thank you!
=> Desislava Portfolio

students/1701-back/jonathan_kidd/20170420-jonathan-kidd-m2.markdown, students/1701-back/jonathan_kidd/20170608-jonathan-kidd-m3.markdown
this PR adds Jonathan Kidd mod 3 portfolio, as well as final scores from Bike Share Mod 2
=> add JK Mod 3

students/1701-front/dave_hubertus/20170608-dave-hubertus-m3.markdown
Dave Hubertus - MOD3 portfolio complete with project scores and peer reviews.
=> Dave Hubertus - MOD3 portfolio

students/1701-back/victoria_vasys/17010421-your-name-m2.markdown, students/1701-back/victoria_vasys/20170421-victoria-vasys-m2.markdown, students/1701-back/victoria_vasys/20170609-victoria-vasys-m3.markdown
Still need 2 gear-up reflections & description/takeaways/instructor comments for Cloney Island Sprint 2
=> Add VV M3 Portfolio

students/1705-back/matt-devoe/20170608-matt-devoe-m1.md
@s-espinosa @mikedao @AliSchlereth 
Final Portfolio Commit for Mod 1 Portfolio
=> Matt DeVoe - Mod 1 Portfolio

students/1705-back/michael_sagapolutele/20170608-Michael-Sagapolutele-m1.md
Adds portfolio for Michael Sagapolutele 1705-BE
=> 1705-BE michael-sagapolutele portfolio

students/1701-front/jack_bevis/20170609-jack-bevis-m3.markdown
Mod 3 FEE Portfolio for Jack Bevis
=> Jack Bevis Mod 3 portfolio

students/1705-back/jim_szalewski/20170608-Jim-Szalewski-m1.md
Everything but final assessment scores included. Will update when scores are available.
=> initial portfolio fill out

students/1705-back/mike-heft/20170608-Mike-Heft-m1.md
=> 20170608-Mike-Heft-m1.md

students/1705-back/daniel-vogelsang/20170608-daniel-vogelsang-m1.md
=> 170-BE-DanielVogelsang

students/1703-back/tom-soucie/20170421-tom-soucie-m1.markdown, students/1703-back/tom-soucie/20170609-tom-soucie-m2.markdown
PR states "2 Files changed" but one of the files is the feedback incorporated from the last project of Mod 1 (Headcount with Mason Holland) so shows as an update / commit.
=> Mod2 BE - Tom Soucie Portfolio

students/1703-back/aaron_olsen/20170421-aaron-olsen-m1.md, students/1703-back/aaron_olsen/20170609-aaron-olsen-m2.md
Mod2 BE Portfolio submission for Aaron Olsen.
=> Mod2-BE Portfolio Aaron Olsen

students/1701-back/lauren_oliveri/20170421-lauren-oliveri-m2.markdown, students/1701-back/lauren_oliveri/20170608-lauren-oliveri-m3.markdown
added teammates feedback from them to me
=> Lauren Oliveri Mod 3 Portfolio

students/1701-back/victoria_vasys/20170609-victoria-vasys-m3.markdown
Add 2 Gear-up reflections
Add description, comments & scores for Cloney Island Sprint 2
=> Update VV M3 Portfolio

students/1701-back/josh_thompson/20170610-josh-thompson-m3.md
I *believe* this is wrapped up and good to go, but making the PR now so if y'all happen to see and review and find anything of note, I can address sooner rather than later.
Obviously I'll update it as more information becomes available after evals, but I think the bulk of the work is done.
=> finish portfolio

students/1705-back/michael_sagapolutele/20170608-Michael-Sagapolutele-m1.md
And actually adds my name and mod at the top.
=> add evaluation for black thursday

students/1705-back/eddie-rose/20170705-Eddie-Rose-m1.md
=> Eddie Rose 1705 BEE

students/1705-back/wil-donovan/20170608-wil-donovan-m1.markdown
Fixed a lot of the HTML errors along with adding the gear up reflections for all five weeks.
=> Wil Donovan-Portfolio

students/1701-back/josh_thompson/20170802-josh-thompson-m4.md
Submitting my portfolio for review.
=> M4 portfolio

students/1701-back/sergey_lukyanenko/20170802-sergey-lukyanenko-m4.markdown
=> Sergey Portfolio m4

students/1701-back/jack_pincus/20170802-Jack-Pincus-M4.md
=> Update M4 portfolio - Jack Pincus

students/1701-front/chris_bandrowsky/20170802-chris-bandrowsky-m4.md
add chris bandrowsky's mod4 portfolio
=> add-chris-bandrowsky-mod4-portfolio

students/1701-front/leta_keane/20170801_Leta_Keane_MOD4.md
=> Leta Keane Mod4 portfolio markdown

students/1706-back/ricky-amparo/20170804-ricky-amparo-m1.md, templates/BEM1_template.md
=> BM1 Ricky Amparo - Portfolio

students/1706-front/sam-singer/20170803-blake-griffin-m1.md
This is my Portfolio Defense in order to graduate 1706 Mod1 FEE.
=> Mod1-Samuel-Singer

students/1706-front/jorge-perez-garcia/20170803-jorge-eduardo-perez-garcia-m1.md
=> Jorge Eduardo Perez Garcia changed name

students/1706-front/ben-porter/20170803-blake-griffin-m1.md
This is my portfolio see you in a bit.
=> Ben Porter Portfolio 1706 Mod 1

students/1703-front/jason-collins/20170804-jason-collins-m3.markdown
=> 1703 FE M3 - Jason Collins

students/1706-front/jorge-perez-garcia/20170803-Jorge-Eduardo_Perez-Garcia-m1.md
Final changes  were update to fix merging conflict.
=> Jorge Ed perezGa / M1/ 1706 / Portfolio

students/1703-back/squee/20170607_squee_mueller_mod2.markdown, students/1703-back/squee/20170802_squee_mueller_mod3.md
adds mod 3 portfolio form for squee
(for some reason, my mod 2 form is showing up in this PR too? Not sure why.)
=> squee mod 3 portfolio submission

students/1703-back/charlie-corrigan/20170804-charlie-corrigan-m3.markdown
1703BE Charlie Corrigan Mod3 Portfolio
=> 1703BE Charlie Corrigan Mod3 Portfolio

students/1703-back/natalia-colome/20170803-natalia-colome-m3.markdown
porfolio 20170729. pending final project scores
=> M3-BE Natalia Colome

students/1706-front/nick-teets/1706M1 - Nick-Teets-portfolio.md
@rrgayhart Updated End of Module Assessment
=> Update End of Module Assessment 1706M1 - Nick-Teets-portfolio.md

students/1705-back/desislava-todorova/20170804-des-todorova-m2.markdown
=> 1705-BEE-Des-Todorova

students/1705-back/jim_szalewski/20170608-Jim-Szalewski-m1.md, students/1705-back/jim_szalewski/20170802-Jim-Szalewski-m2.md
=> Jim Szalewski 1705 B

students/1705-back/michael_sagapolutele/20170802-michael-sagapolutele-m2.md
Adds reflections on Module 2 and how far we've come.
=> Michael Sagapolutele 1705-b Mod 2 Portfolio

students/1705-back/Michael-Centrelli/20170802-Michael-Centrelli.m2.md
=> Michael-Centrelli-1705-BE

students/1705-back/samantha-gongora/20170804-Samantha-Gongora-m2.md
@mikedao @laurenfazah
Hope you enjoy me ranting about myself for ~ 2500 words. :)
=> 1705-BEE Samantha Gongora

students/1705-back/will-ratterman/20170731-will-ratterman-m2.md
=> Will Ratterman 1705-BEE

students/1706-front/nick-teets/1706M1 - Nick-Teets-portfolio.md
Added partner feedback for Linked List and IdeaBox
=> Update 1706M1 - Nick-Teets-portfolio.md

students/1706-front/lucas-finney/20170803-lucas-finney-m1.md
Updated portfolio to include partner feedback from the IdeaBox project.
=> l-finney - add in partner feedback

students/1703-back/aaron_olsen/20170921-aaron-olsen-m4.md
Aaron Olsen Mod 4 Portfolio Submission.
=> Aaron Olsen Mod 4

students/1708-back/luis-garcia/20170922-luis-garcia-m1.md
=> Luis Garcia-Portfolio

students/1708-back/timo-tyrrell/20170922-Timothy-Tyrrell-M1.md
=> Portfolio Submission Timothy Tyrrell 1708 BE Mod1

students/1706-back/becki-srofe/20170920-becki-srofe-m2.md
=> Mod 2 Becki Srofe

students/1706-back/ricky-amparo/20170921-ricky-amparo-m2.md
=> add Ricky Amparo BEMod2 1706 portfolio

students/1706-back/sam-nayrouz/20170922-sam-nayrouz-m2.markdown
=> 20170922-sam-nayrouz-m2 portfolio

students/1706-back/mike-heft/20170922-mike-heft-m2.md
@s-espinosa @icorson3 Thank you again for everything you've done this mod. I may not have looked like I was enjoying it at time because of home stresses, but I always felt better mentally the longer I was here 😃
=> 20170922-mike-heft-m2 portfolio

students/1708-back/marshall-houston/20170922-marshall-houston-m1.md
20170922-marshall-houston-m1 porfolio submission
=> Marshall Houston 1708 BE M1 Portfolio

students/1705-front/christie-lynam/20170922-christie-lynam-m3.markdown
=> 20170921-christie-lynam-m3

students/1706-front/lucas-finney/Luke-Finney-M2.markdown
- Added all necessary information, but still missing Weathrly and End of Module Assessment scores
=> Update mod-2 portfolio

students/1706-front/sam-singer/m2.md
=> Samuel-Singer-M2.md

students/1705-back/samantha-gongora/20170922-Samantha-Gongora-m3.md
=> adds M3 portfolio

students/1705-front/ana-jauregui/20170922- ana-jauregui-m3.md
=> Create 20170922- ana-jauregui-m3.md

templates/BEM4_template.md
@laurenfazah how's this look?!
=> Update B4 template to include PD deliverables for portfolio reviews

students/1705-back/will-ratterman/20171108-will-ratterman-m4.md
@laurenfazah @kat3kasper 
Portfolio Done 😄  Let me know if you need anything else
=> Will Ratterman Portfolio PR

students/1705-back/chantal_justamond/20171108-chantal-justamond-m4.md
=> portfolio | 1705 Backend | Chantal Justamond 

students/1705-back/katie-shermer/201711109-katie-keel-m4.md
=> Katie Keel 1705 BE4 Graduation Portfolio

students/1708-back/aurora-ziobrowski/20170922-aurora-ziobrowski-m1.md, students/1708-back/aurora-ziobrowski/20171110-aurora-ziobrowski-m2.md
=> Aurora Ziobrowski 1708-BE

students/1708-back/marshall-houston/20171109-marshall-houston-m2.md
=> Marshall Houston 1708 - BE M2 Portfolio

students/1710-front/valentino-valentine/ValentinoValentine-M1-Portfolio.md, students/1710-front/valentino-valentine/template-markdown.md
Here's my portfolio for portfolio deensing!
=> Valentino valentine m1 portfolio

students/1706-front/lola-brenner/20171107-lola-brenner-m3.md
Adds markdown file for mod 3 portfolio for Lola Brenner
=> Lola Brenner 1706FE M3 Portfolio

students/1706-back/Kali-Borkoski/20170922-kali-borkoski-m2.md, students/1706-back/Kali-Borkoski/2017109-kali-borkoski-m3.md
=> Commit M3 portfolio Borkoski

students/1710-back/tyler-madsen/20171109-tyler-madsen-m1.md
Added finalized Module 1 portfolio. Please review!
=> Tyler Madsen - 1710 BE

students/1710-back/zach-landes/20171109-zach-landes-m1.md
=> Zachary Landes 1710 BE

students/1708-front/julie-hawkins/20171110-julie-hawkins-m2.md
=> 20171110-julie-hawkins-m2.md

students/1706-front/nick-teets/1706FEm3 - NTeets-portfolio.md
Markdown for mod 3 front end program portfolio - Nick Teets
=> 1706FEm3 - NTeets-portfolio.md

students/1706-back/ashish-vaid/mod-3
=> Ash- mod 3 - 1706 BE

students/1706-back/brandon-stewart/20171109-brandonstewart-m3.md
Esteemed instructors,
Please see this PR for my portfolio responses.  Thank you.
=> add brandon stewart

students/1710-front/bruce-chung/20171110-bruce-chung-m1.md
=> 1710-front/bruce-chung/20171110-bruce-chung-m1.md

students/1710-back/timo-tyrrell/20171109-timo-tyrrell-m1.md
=> Timo Tyrrell portfolio BE1710

students/1706-back/mimi-le/20171109-mimi-le-m3.md
@jmejia @corywest - mod 3 portfolio
=> add portfolio for mod 3

students/1706-back/joel-lindow/BEM3_template.md
Added as much relevant data as possible for a complete representation of my mod 3 journey.
=> Update of Mod 3 Portfolio

students/1708-back/tim-joo/20171109-tim-joo-m2.markdown
=> 1708 BE Mod 2 Tim Joo

students/1706-back/jay-p-hodges/20171109-jay-p-hodges-m3.md
=> Mod3 #1706 Jay P Hodges

students/1706-back/mike-heft/20171110-mike-heft-m3.md
=> 20171110-mike-heft-m3.md

students/1705-front/nik-bornemeier/20170922-nik-bornemeier-m3.MD
=> Nb nik bornemeir mod3 first attempt

students/1706-front/nik-bornemeier/m3.md
=> add mod3 portfolio defense

students/1710-back/nico-lewis/20171109-nico-lewis-m1.md
=> Nico Lewis 1710 BE 

students/1706-back/mimi-le/20180110-mimi-le-m4.md
=> Mimi Le - Mod 4 - Portfolio

students/1706-back/ricky-amparo/ricky-amparo-m4.md
=> add ricky-amparo-m4 portfolio

students/1710-back/timo-tyrrell/20171109-timo-tyrrell-m1.md, students/1710-back/timo-tyrrell/Timo-Tyrrell-m2.md
An enjoyable and challenging mod. Thank you Ali and Ilana for the effort and the feedback!
=> Mod 2 portfolio 1710-Timo-Tyrrell

students/1710-back/gabriel-afflitto/20180110-gabriel-afflitto-m2.md
=> Porfolio Module2 Gabe Afflitto

students/1710-back/lee-chow/20180106-lee-chow-m2.md
Edited Name within portfolio markdown file (mod2)
=> LeeChow_1710BE_Mod2

students/1706-back/eddie-rose/20180110-Eddie-Rose-m4.md
adds link to post graduation calendar
=> Update 1706BEE 20180110-Eddie-Rose-m4.md

students/1710-back/zach-landes/20171109-zach-landes-m1.md, students/1710-back/zach-landes/20180109-zach-landes-m2.md, templates/BEM2_template.md
=> Zach landes 1710 BE

template-markdown.md
Ryan Harrington M1FE - Portfolio
=> 20180110-ryan-harrington-m1.markdown

students/1711-front/alan-charles/2017-Alan-Charles-M1.markdown, students/1711-front/alan-charles/template-markdown.md
=> Alan-Charles-01-12-17-1711FE

students/1711-back/matt-milton/20180111-matt-milton-m1.md
=> Adds personal portfolio review

students/1710-back/young-jung/20170922-young-jung-mod1.md, students/1710-back/young-jung/20180112-young-jung-mod2.md
=> Young Jung - 1710 BEE - MOD 2

students/1711-front/charles-yach/20180112-charles-yach-m1.md
Updating with new pull request after merge conflict with root template-markdown.md
=> 20180112-charles-yach-m1.md

students/1711-back/cameron-johnson/20180111-cameron-johnson-m1.md, templates/BEM1_template.md
=> 20180111-cameron-johnson-m1

students/1801-back/andrew-piermarini/20180301-andrew-piermarini-m1.md
Andrew Piermarini's Mod1 Portfolio
=> 20180301-andrew-piermarini-m1

students/1801-back/nikhil-shahi/20180301-nikhil-shahi-m1.md
Portfolio review for Nikhil Shahi, 1801 BE m1
=> Nikhil Shahi 1801 M1 Portfolio Review

students/1711-back/luke-chambers/20170111-luke-chambers-m1.md, students/1711-back/luke-chambers/20180228-luke-chambers-m2.md
=> Luke Chambers 1711 BE

students/1708-back/dione-wilson/20180301-dione-wilson-m4.md
=> 20180301-dione-wilson-m4

students/1801-front/ryan-harrington/template.md, template.md
20180228-ryan-harrington-m1-md
=> 20180228-ryan-harrington-m1-md

students/1710-back/tyler-madsen/BEM3-portfolio.md, templates/BEM3_template.md
=> Tyler Madsen - BEM3 portfolio

students/1710-front/nora-gully/20180301-nora-gully-m3.md
=> Nora Mod 3 Portfolio

students/1711-back/matt-milton/20180301-matt-milton-m2.md
=> adds evaluation score

students/1710-back/nico-lewis/20170112-nico-lewis-m2.md, students/1710-back/nico-lewis/20170229-nico-lewis-m3.md, students/1710-back/nico-lewis/20171109-nico-lewis-m1.md
This should be good to go now!
=> Single Scores

students/1801-back/adam-lusk/20180418-adam-lusk-m2
=> 20180418-adam-lusk-m2

students/1801-back/jimmy-nelson/20180418-jimmy-nelson-m2.md
Jimmy Nelson 1801 BE Mod 2 Portfolio
=> Jimmy Nelson 1801 BE Mod 2 Portfolio

students/1803-back/manoj-panta/template.md
=> Manoj Panta

students/1801-back/alex-cutschall/20180416-alex-cutschall-m2.markdown
=> Alex Cutschall Mod 2 Portfolio Finished

students/1803-back/sabrina-robinson/template.md
=> Sabrina Robinsin

students/1803-back/20180418 - blythe_mcfall - 1803.markdown
Including Update to Personal Portfolio
=> Including Update to Personal Portfolio

students/1803-back/tristan-bambauer/template.md
=> Tristan Bambauer - 1803

students/1710-back/young-jung/20180419-young-joon-jung-m4.md
=> 20180419-young-joon-jung-m4.md

students/1710-back/gabriel-afflitto/20180418-gabriel-afflitto-m4.md
=> M4-portfolio

students/1710-back/B-Lauren-Billngton/20180418-laure-billingtonr-m4.md
=> Mod 4 Portfolio - Lauren Billington

students/1803-front/spenser-leighton/template.md
Spenser Leighton Mod1 Portfolio.
=> 20180418-spenser-leighton-m1.md

students/1803-front/todd-ayres/template.md
=> 20180419-Todd-Ayres-m1.md

students/1804-back/andrew-tobin/20180606-andrew-tobin-m1.md
=> Andrew Tobin

students/1711-back/luke-chambers/20180907-luke-chambers-m4.md
=> Luke Chambers, BE1711

students/1801-front/cameron-buscher/20180418-cameron-buscher-m2.md, students/1801-front/cameron-buscher/20180606-cameron-buscher-m3.md
Please let me know if there's anything I overlooked, but I just looked it over over and over and couldn't find anything. Except I don't have my weathrly scores, but just because those weren't uploaded yet :).
=> Added portfolio defense for module two

students/1801-front/eric-jungbluth/20180603-eric-jungbluth-m3.md
Add portfolio defense for Eric Jungbluth
=> Add 20180603-eric-jungbluth-m3.md

students/1806-back/tara-craig/20180801-tara-craig-BE1.md
* Filled out portfolio review template
* Add name to top of template
=> Completed portfolio review template

students/1806-back/tim-fielder/20180803-Tim-Fielder-B1.markdown
M1 Portfolio Submission Tim Fielder
=> M1 Portfolio Submission Tim Fielder

students/1806-back/nick-lindeberg/08032018-nick-lindeberg-B1.markdown
Add 1806 folder and portfolio md.
=> Nick Lindeberg 1806 BE Portfolio

portfolios/students/1806/rebecca-hyland/20180803-rebecca-hyland-B1.md
Rebecca's completed portfolio template for 1806 BEE M1
=> Rebecca Hyland 

students/1806-back/silvestre-cuellar/20180803-silvestre-cuellar-B1.md
=> silvestre cuellar

students/1806-back/maria-torres/20180803-maria-torres-m1.md
=> Maria Torre Portfolio Review.

students/1806-front/tobin-nelson/20180803-tobin-nelson-m1.md
=> 20180803-tobin-nelson-m1

students/1806-front/kevin-ryan/20180803-kevin-ryan-m1.markdown, students/1806-front/kevin-ryan/template.md
Portfolio is ready for review!
=> 1806 Portfolio

students/1804-back/emmie-hayes/20180801-emmie-hayes-m2.markdown
=> emmie hayes mod 2 portfolio

students/1806-back/maria-torres/2018-09-20
https://github.com/turingschool-projects/activerecord-obstacle-course/pull/12
=> Create 2018-09-20 Maria Torres

students/1808-back/Aizar-Cabrera/20180921-aizar-cabrera-B1.md
=> Mod 1 Portfolio

students/1808-back/Amy-Petrie/20180921-amy-petrie-B1.markdown
Amy Petrie's Mod 1 portfolio reflection
=> Amy Petrie's Mod 1 portfolio reflection

students/1808-back/Rene-Casco/20180921-rene-casco-M1.markdown
=> Rene Casco

students/1803-front/ryan-harrington/20180920-ryan-harrington-m4.md
=> Ryan Harrington FE4 portfolio

students/1803-front/andrew-james/20180919-andrew-james-m4.md
@robbiejaeger Here is my portfolio for mod-4.
=> Add mod-4 portfolio

students/1808-back/Dan-Hutchinson/20180921-dan-hutchinson-m1.md
portfolio markdown completed, pushed only my own, single markdown file. thanks!
=> completed mod1 portfolio markdown

students/1808-back/Aaron-Brooks-Roberts/20170919-aaron-brooksroberts-m1.markdown, students/1808-back/Aaron-Brooks-Roberts/20180919-aaron-brooksroberts-m1.markdown
=> Aaron portfolio

students/1806-back/tara-craig/20180919-tara-craig-BE2.md
=> Tara Craig BE Mod2

students/1806-back/andrew-tobin/20180801-andrew-tobin-m1.md, students/1806-back/andrew-tobin/20180919-andrew-tobin-m2.md
=> Andrew Tobin mod 2 portfolio

students/1806-front/alexander-ela/20180919-alexander-ela-m2.md
Pull request for Alexander Ela Mod 2 Portfolio Defense Deliverables.
Cohort 1806 FE.
=> 20180919-alexander-ela-m2.md

students/1806-front/dina-caraballo/20180921-dina-caraballo-m2.md
This file contains my portfolio for module 2.
=> Mod 2 Portfolio - Dina Caraballo

students/1810-back/Ben-Lee/20181106-ben-lee-B1.markdown
Sorry this is late!
See you guys tomorrow.
=> Adds Ben's portfolio markdown

students/1810-back/Bradley-Niedt/20181109-bradley-niedt-B1.markdown
=> 20181109-bradley-niedt-B1

students/1804-back/keegan-corrigan/20181108-keegan-corrigan-m4.md
* Adds mod 4 reflections to turing portfolio repo.
=> Add keegan corrigan mod 4 portfolio document

students/1804-front/gray-smith/20181108-gray-smith-m4.md
- Add Gray Smith m4 portfolio review
=> Add Gray Smith m4 portfolio review

students/1804-back/jp-lynch/20181108-jp-lynch-m4.md
=> JP Lynch BE Mod4

students/1808-back/Aaron-Brooks-Roberts/20170919-aaron-brooksroberts-m1.markdown, students/1808-back/Aaron-Brooks-Roberts/20180919-aaron-brooksroberts-m1.markdown, students/1810-back/Aaron-Brooks-Roberts-1810/20181109-aaron-brooksroberts-m1.markdown
Mod1 Portfolio Aaron Brooks Roberts
=> Aaron Brooks Roberts 1810

students/1810-back/Vince-Provenzano/20181106-vincent-provenzano-b1.md
Created the portfolio for Vincent Provenzano
=> Vincent Provenzano - Portfolio - BE - Mod1

students/1806-front/aaron-weissman/aaron-weissman-m2-portfolio.md, students/1806-front/aaron-weissman/aaron-weissman-m3-portfolio.md
My m3 portfolio is done.
This is also pushing up my m2 portfolio even though that's already in master.
Please let me know if I need to rectify that.
Thanks,
Aaron
=> m3 portfolio

students/1804-front/michael-lyons/20180802-michael-lyons-m2.md, students/1804-front/michael-lyons/20180919-michael-lyons-m3.md, students/1804-front/michael-lyons/20181107-michael-lyons-m4.md
=> Add mod4 portfolio Michael Lyons
